on: [push]
name: lane-assist-container-build

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: "Checkout GitHub Action"
              uses: actions/checkout@main

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: "Login to Docker"
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - run: |
                  cargo install cross
                  cross build --release --target=armv7-unknown-linux-gnueabihf
                  export TAG=`date -u +"%Y%m%dT%H%M%SZ"`
                  docker buildx build . --platform linux/arm/v7 -t tpark.azurecr.io/lane-assist-${{ steps.extract_branch.outputs.branch }}:$TAG
                  docker push tpark.azurecr.io/lane-assist-${{ steps.extract_branch.outputs.branch }}:$TAG
